// Auto-generated by maycad_extract/bake_diy_connectors.py — do not edit.
// 3D corner-bracket (角码) models baked from maycad_output, mounted in the
// DIY editor under the "Connectors" tab. Each part is normalized to the DIY
// mounting frame: inner faces on the x=0/y=0 planes, legs +x/+y, z centred,
// extents in mm.

export type ConnectorKind = 'cast' | 'alu' | 'pa' | 'steel';

export interface DiyConnector {
  /** Catalog id — carried in the drag payload and stored on DiyBracket.connectorId. */
  id: string;
  /** Shown name, e.g. "Angle Alu 25x40". */
  label: string;
  /** One-line subtitle on the card. */
  desc: string;
  /** Footprint shown on the card chip (e.g. "25x40"). */
  dim: string;
  kind: ConnectorKind;
  stlUrl: string;
  /** Base material colour. */
  color: string;
  /** Baked axis extent (mm) — max(x,y,z span). Scales ext->size in the viewer. */
  extMm: number;
  /** Baked bounding box (mm). Mounting faces sit on x=0/y=0, z centred. */
  boxMm: { min: [number, number, number]; max: [number, number, number] };
}

/** The built-in programmatic corner bracket (kept first / default). */
export const CAST_CONNECTOR: DiyConnector = {
  id: 'corner_bracket',
  label: 'Corner Bracket',
  desc: 'Cast L-bracket 3030',
  dim: '30x30',
  kind: 'cast',
  stlUrl: '/Cast_Corner_Bracket.stl',
  color: '#707070',
  extMm: 21,
  boxMm: { min: [-1, -1, -8.5], max: [20, 20, 8.5] },
};

export const CONNECTORS: DiyConnector[] = [
  CAST_CONNECTOR,
  {
    id: '1.46.110',
    label: 'Angle Alu 25x40',
    desc: '铝 角码 · Ø6.6',
    dim: '25x40',
    kind: 'alu',
    stlUrl: '/connectors/1.46.110.stl',
    color: '#c8c8c8',
    extMm: 40,
    boxMm: { min: [0, 0, -10], max: [40, 25, 10] },
  },
  {
    id: '1.46.115',
    label: 'Angle Alu 25x40',
    desc: '铝 角码 · Ø8.7',
    dim: '25x40',
    kind: 'alu',
    stlUrl: '/connectors/1.46.115.stl',
    color: '#c8c8c8',
    extMm: 40,
    boxMm: { min: [0, 0, -10], max: [40, 25, 10] },
  },
  {
    id: '1.46.120',
    label: 'Angle Alu 25x40',
    desc: '铝 角码 · M6',
    dim: '25x40',
    kind: 'alu',
    stlUrl: '/connectors/1.46.120.stl',
    color: '#c8c8c8',
    extMm: 40,
    boxMm: { min: [0, 0, -10], max: [40, 25, 10] },
  },
  {
    id: '1.46.203.2028.1',
    label: 'PA Angle 20x28',
    desc: '尼龙 PA · 灰',
    dim: '20x28',
    kind: 'pa',
    stlUrl: '/connectors/1.46.203.2028.1.stl',
    color: '#b5b5b5',
    extMm: 30.12,
    boxMm: { min: [-2.12, -2.12, -10], max: [28, 28, 10] },
  },
  {
    id: '1.46.203.2028.2',
    label: 'PA Angle 20x28',
    desc: '尼龙 PA · 黑',
    dim: '20x28',
    kind: 'pa',
    stlUrl: '/connectors/1.46.203.2028.2.stl',
    color: '#b5b5b5',
    extMm: 30.12,
    boxMm: { min: [-2.12, -2.12, -10], max: [28, 28, 10] },
  },
  {
    id: '1.46.203.3038.1',
    label: 'PA Angle 30x38',
    desc: '尼龙 PA · 灰',
    dim: '30x38',
    kind: 'pa',
    stlUrl: '/connectors/1.46.203.3038.1.stl',
    color: '#b5b5b5',
    extMm: 41,
    boxMm: { min: [-3, -3, -15], max: [38, 38, 15] },
  },
  {
    id: '1.46.203.3038.2',
    label: 'PA Angle 30x38',
    desc: '尼龙 PA · 黑',
    dim: '30x38',
    kind: 'pa',
    stlUrl: '/connectors/1.46.203.3038.2.stl',
    color: '#b5b5b5',
    extMm: 41,
    boxMm: { min: [-3, -3, -15], max: [38, 38, 15] },
  },
  {
    id: '1.46.20536',
    label: 'Angle Alu 48x48',
    desc: '铝 角码 · Ø6.6',
    dim: '48x48',
    kind: 'alu',
    stlUrl: '/connectors/1.46.20536.stl',
    color: '#c8c8c8',
    extMm: 48,
    boxMm: { min: [0, 0, -15], max: [48, 48, 15] },
  },
  {
    id: '1.46.20539',
    label: 'Angle Alu 48x48',
    desc: '铝 角码 · Ø9.0',
    dim: '48x48',
    kind: 'alu',
    stlUrl: '/connectors/1.46.20539.stl',
    color: '#c8c8c8',
    extMm: 48,
    boxMm: { min: [0, 0, -15], max: [48, 48, 15] },
  },
  {
    id: '1.68.1.1.4030.X/01V',
    label: 'Steel Gusset 40x40',
    desc: '钢 角板',
    dim: '40x40',
    kind: 'steel',
    stlUrl: '/connectors/1.68.1.1.4030.X_01V.stl',
    color: '#a8a8a8',
    extMm: 40,
    boxMm: { min: [0, 0, -15], max: [40, 40, 15] },
  },
  {
    id: '7.11.706.89/01',
    label: 'Steel Gusset 47.5x47.5',
    desc: '钢 角板',
    dim: '47.5x47.5',
    kind: 'steel',
    stlUrl: '/connectors/7.11.706.89_01.stl',
    color: '#a8a8a8',
    extMm: 47.5,
    boxMm: { min: [0, 0, -15], max: [47.5, 47.5, 15] },
  },
];

const byId = new Map(CONNECTORS.map((c) => [c.id, c]));

/** Look up a connector catalog entry; unknown ids fall back to the cast bracket. */
export function connectorById(id?: string | null): DiyConnector {
  return (id && byId.get(id)) || CAST_CONNECTOR;
}
