// Auto-generated by maycad_extract/bake_fasteners.py — do not edit.
//
// Real MayTec fasteners (螺栓 / 沉头螺钉 / T 型螺母), baked from the MayCad
// catalog. Replaces the hand-modelled cylinders-and-boxes these used to be:
// what the 3D view draws is now the catalogue part, and the numbers the panel
// and the CSV print are the numbers this table was measured from.
//
// APP FRAME (all extents mm): the part's MATING PLANE is z=0 and its axis is
// +Z, pointing INTO the material — the frame the seats use, since a fastener is
// placed by its bearing surface and grows inward.
//   · din912 / din7984 (圆柱头 / 薄头) and wn7381 (圆头法兰): the catalog's
//     origin already sits on the shoulder, so z=0 is the bearing face and the
//     head hangs at z < 0.
//   · countersunk (沉头): the origin is the head's OUTER face, so the whole
//     screw is z >= 0 and the head is BELOW the surface it is sunk into.
//   · T-nut: the block is centred on z=0 (the mesh has no datum for the lips).
//
// `length` is the catalog's own nominal length — the number in the part name,
// i.e. thread length for a cap screw and overall length for a countersunk one.

import type { ScrewSize } from '../types/furniture';

/** Head/standard families the catalog actually holds. */
export type ScrewFamily = 'din912' | 'din7984' | 'countersunk' | 'wn7381';

/**
 * T-nut families, which are about how the nut HOLDS, not what it threads onto.
 *  · t_slot — a plain block that slides into the slot (1.34.10E).
 *  · spring — a block with a spring plate that grips the slot (1.32.4F, "w/spring").
 *
 * Independent of the size AND of the series: the catalog holds an M6 in both
 * families for the same 30-series slot, so (size, series) alone does not name a
 * part.  That is why findTNut takes all three.
 */
export type TNutFamily = 't_slot' | 'spring';

export interface BakedScrew {
  /** Catalog part id (MayCad uid). */
  uid: string;
  family: ScrewFamily;
  size: ScrewSize;
  /** Catalog nominal length (mm) — thread length, or overall for a countersunk screw. */
  length: number;
  stlUrl: string;
  /** Baked bounding box (mm) in the app frame above. */
  boxMm: { min: [number, number, number]; max: [number, number, number] };
}

export interface BakedTNut {
  uid: string;
  family: TNutFamily;
  size: ScrewSize;
  /** Profile series whose slot the block fits (see tNutName). */
  series: number;
  stlUrl: string;
  boxMm: { min: [number, number, number]; max: [number, number, number] };
}

/** Every baked screw, grouped family by family and ascending in length. */
export const SCREWS: BakedScrew[] = [
  {
    uid: '0.63.D07991.04006',
    family: 'countersunk',
    size: 'M4',
    length: 6,
    stlUrl: '/fasteners/0.63.D07991.04006.stl',
    boxMm: { min: [-3.82, -3.82, 0], max: [3.82, 3.82, 6] },
  },
  {
    uid: '0.63.D07991.04008',
    family: 'countersunk',
    size: 'M4',
    length: 8,
    stlUrl: '/fasteners/0.63.D07991.04008.stl',
    boxMm: { min: [-3.8, -3.82, 0], max: [3.8, 3.74, 8] },
  },
  {
    uid: '0.63.D07991.04010',
    family: 'countersunk',
    size: 'M4',
    length: 10,
    stlUrl: '/fasteners/0.63.D07991.04010.stl',
    boxMm: { min: [-3.8, -3.82, 0], max: [3.8, 3.74, 10] },
  },
  {
    uid: '0.63.D07991.04012',
    family: 'countersunk',
    size: 'M4',
    length: 12,
    stlUrl: '/fasteners/0.63.D07991.04012.stl',
    boxMm: { min: [-3.72, -3.82, 0], max: [3.72, 3.82, 12] },
  },
  {
    uid: '0.63.D07991.04016',
    family: 'countersunk',
    size: 'M4',
    length: 16,
    stlUrl: '/fasteners/0.63.D07991.04016.stl',
    boxMm: { min: [-3.79, -3.82, 0], max: [3.79, 3.71, 16] },
  },
  {
    uid: '0.63.D07991.04020',
    family: 'countersunk',
    size: 'M4',
    length: 20,
    stlUrl: '/fasteners/0.63.D07991.04020.stl',
    boxMm: { min: [-3.82, -3.82, 0], max: [3.82, 3.82, 20] },
  },
  {
    uid: '0.63.D07991.05008',
    family: 'countersunk',
    size: 'M5',
    length: 8,
    stlUrl: '/fasteners/0.63.D07991.05008.stl',
    boxMm: { min: [-4.82, -4.82, 0], max: [4.82, 4.82, 8] },
  },
  {
    uid: '0.63.D07991.05012',
    family: 'countersunk',
    size: 'M5',
    length: 12,
    stlUrl: '/fasteners/0.63.D07991.05012.stl',
    boxMm: { min: [-4.79, -4.82, 0], max: [4.79, 4.71, 12] },
  },
  {
    uid: '0.63.D07991.05014',
    family: 'countersunk',
    size: 'M5',
    length: 14,
    stlUrl: '/fasteners/0.63.D07991.05014.stl',
    boxMm: { min: [-4.7, -4.82, 0], max: [4.7, 4.82, 14] },
  },
  {
    uid: '0.63.D07991.05016',
    family: 'countersunk',
    size: 'M5',
    length: 16,
    stlUrl: '/fasteners/0.63.D07991.05016.stl',
    boxMm: { min: [-4.7, -4.82, 0], max: [4.7, 4.82, 16] },
  },
  {
    uid: '0.63.D07991.05020',
    family: 'countersunk',
    size: 'M5',
    length: 20,
    stlUrl: '/fasteners/0.63.D07991.05020.stl',
    boxMm: { min: [-4.78, -4.82, 0], max: [4.78, 4.68, 20] },
  },
  {
    uid: '0.63.D07991.05025',
    family: 'countersunk',
    size: 'M5',
    length: 25,
    stlUrl: '/fasteners/0.63.D07991.05025.stl',
    boxMm: { min: [-4.82, -4.82, 0], max: [4.82, 4.82, 25] },
  },
  {
    uid: '0.63.D07991.05030',
    family: 'countersunk',
    size: 'M5',
    length: 30,
    stlUrl: '/fasteners/0.63.D07991.05030.stl',
    boxMm: { min: [-4.77, -4.82, 0], max: [4.77, 4.62, 30] },
  },
  {
    uid: '0.63.D07991.06010',
    family: 'countersunk',
    size: 'M6',
    length: 10,
    stlUrl: '/fasteners/0.63.D07991.06010.stl',
    boxMm: { min: [-5.78, -5.78, 0], max: [5.78, 5.78, 10] },
  },
  {
    uid: '0.63.D07991.06016',
    family: 'countersunk',
    size: 'M6',
    length: 16,
    stlUrl: '/fasteners/0.63.D07991.06016.stl',
    boxMm: { min: [-5.75, -5.78, 0], max: [5.75, 5.66, 16] },
  },
  {
    uid: '0.63.D07991.06020',
    family: 'countersunk',
    size: 'M6',
    length: 20,
    stlUrl: '/fasteners/0.63.D07991.06020.stl',
    boxMm: { min: [-5.64, -5.78, 0], max: [5.64, 5.78, 20] },
  },
  {
    uid: '0.63.D07991.06025',
    family: 'countersunk',
    size: 'M6',
    length: 25,
    stlUrl: '/fasteners/0.63.D07991.06025.stl',
    boxMm: { min: [-5.74, -5.78, 0], max: [5.74, 5.62, 25] },
  },
  {
    uid: '0.63.D06912.04008',
    family: 'din7984',
    size: 'M4',
    length: 8,
    stlUrl: '/fasteners/0.63.D06912.04008.stl',
    boxMm: { min: [-3.5, -3.5, -2.8], max: [3.5, 3.5, 8] },
  },
  {
    uid: '0.63.D06912.04010',
    family: 'din7984',
    size: 'M4',
    length: 10,
    stlUrl: '/fasteners/0.63.D06912.04010.stl',
    boxMm: { min: [-3.49, -3.5, -2.8], max: [3.49, 3.5, 10] },
  },
  {
    uid: '0.63.D06912.04012',
    family: 'din7984',
    size: 'M4',
    length: 12,
    stlUrl: '/fasteners/0.63.D06912.04012.stl',
    boxMm: { min: [-3.47, -3.5, -2.8], max: [3.47, 3.5, 12] },
  },
  {
    uid: '0.63.D06912.04016',
    family: 'din7984',
    size: 'M4',
    length: 16,
    stlUrl: '/fasteners/0.63.D06912.04016.stl',
    boxMm: { min: [-3.5, -3.5, -2.8], max: [3.5, 3.5, 16] },
  },
  {
    uid: '0.63.D06912.04020',
    family: 'din7984',
    size: 'M4',
    length: 20,
    stlUrl: '/fasteners/0.63.D06912.04020.stl',
    boxMm: { min: [-3.48, -3.5, -2.8], max: [3.48, 3.42, 20] },
  },
  {
    uid: '0.63.D06912.05008',
    family: 'din7984',
    size: 'M5',
    length: 8,
    stlUrl: '/fasteners/0.63.D06912.05008.stl',
    boxMm: { min: [-4.24, -4.25, -3.5], max: [4.24, 4.2, 8] },
  },
  {
    uid: '0.63.D06912.05010',
    family: 'din7984',
    size: 'M5',
    length: 10,
    stlUrl: '/fasteners/0.63.D06912.05010.stl',
    boxMm: { min: [-4.25, -4.25, -3.5], max: [4.25, 4.25, 10] },
  },
  {
    uid: '0.63.D06912.05012',
    family: 'din7984',
    size: 'M5',
    length: 12,
    stlUrl: '/fasteners/0.63.D06912.05012.stl',
    boxMm: { min: [-4.24, -4.25, -3.5], max: [4.24, 4.25, 12] },
  },
  {
    uid: '0.63.D06912.05016',
    family: 'din7984',
    size: 'M5',
    length: 16,
    stlUrl: '/fasteners/0.63.D06912.05016.stl',
    boxMm: { min: [-4.22, -4.25, -3.5], max: [4.22, 4.25, 16] },
  },
  {
    uid: '0.63.D06912.05020',
    family: 'din7984',
    size: 'M5',
    length: 20,
    stlUrl: '/fasteners/0.63.D06912.05020.stl',
    boxMm: { min: [-4.25, -4.25, -3.5], max: [4.25, 4.25, 20] },
  },
  {
    uid: '0.63.D06912.05025',
    family: 'din7984',
    size: 'M5',
    length: 25,
    stlUrl: '/fasteners/0.63.D06912.05025.stl',
    boxMm: { min: [-4.23, -4.25, -3.5], max: [4.23, 4.16, 25] },
  },
  {
    uid: '0.63.D06912.05030',
    family: 'din7984',
    size: 'M5',
    length: 30,
    stlUrl: '/fasteners/0.63.D06912.05030.stl',
    boxMm: { min: [-4.14, -4.25, -3.5], max: [4.14, 4.25, 30] },
  },
  {
    uid: '0.63.D06912.05035',
    family: 'din7984',
    size: 'M5',
    length: 35,
    stlUrl: '/fasteners/0.63.D06912.05035.stl',
    boxMm: { min: [-4.25, -4.25, -3.5], max: [4.25, 4.25, 35] },
  },
  {
    uid: '0.63.D06912.05040',
    family: 'din7984',
    size: 'M5',
    length: 40,
    stlUrl: '/fasteners/0.63.D06912.05040.stl',
    boxMm: { min: [-4.25, -4.25, -3.5], max: [4.25, 4.25, 40] },
  },
  {
    uid: '0.63.D06912.05045',
    family: 'din7984',
    size: 'M5',
    length: 45,
    stlUrl: '/fasteners/0.63.D06912.05045.stl',
    boxMm: { min: [-4.25, -4.25, -3.5], max: [4.25, 4.25, 45] },
  },
  {
    uid: '0.63.D06912.05050',
    family: 'din7984',
    size: 'M5',
    length: 50,
    stlUrl: '/fasteners/0.63.D06912.05050.stl',
    boxMm: { min: [-4.14, -4.25, -3.5], max: [4.14, 4.25, 50] },
  },
  {
    uid: '0.63.D06912.05055',
    family: 'din7984',
    size: 'M5',
    length: 55,
    stlUrl: '/fasteners/0.63.D06912.05055.stl',
    boxMm: { min: [-4.14, -4.25, -3.5], max: [4.14, 4.25, 55] },
  },
  {
    uid: '0.63.D06912.05060',
    family: 'din7984',
    size: 'M5',
    length: 60,
    stlUrl: '/fasteners/0.63.D06912.05060.stl',
    boxMm: { min: [-4.19, -4.25, -3.5], max: [4.19, 3.99, 60] },
  },
  {
    uid: '0.63.D06912.06008',
    family: 'din7984',
    size: 'M6',
    length: 8,
    stlUrl: '/fasteners/0.63.D06912.06008.stl',
    boxMm: { min: [-4.99, -5, -4], max: [4.99, 4.94, 8] },
  },
  {
    uid: '0.63.D06912.06010',
    family: 'din7984',
    size: 'M6',
    length: 10,
    stlUrl: '/fasteners/0.63.D06912.06010.stl',
    boxMm: { min: [-5, -5, -4], max: [5, 5, 10] },
  },
  {
    uid: '0.63.D06912.06012',
    family: 'din7984',
    size: 'M6',
    length: 12,
    stlUrl: '/fasteners/0.63.D06912.06012.stl',
    boxMm: { min: [-5, -5, -4], max: [5, 5, 12] },
  },
  {
    uid: '0.63.D06912.06014',
    family: 'din7984',
    size: 'M6',
    length: 14,
    stlUrl: '/fasteners/0.63.D06912.06014.stl',
    boxMm: { min: [-4.98, -5, -4], max: [4.98, 5, 14] },
  },
  {
    uid: '0.63.D06912.06016',
    family: 'din7984',
    size: 'M6',
    length: 16,
    stlUrl: '/fasteners/0.63.D06912.06016.stl',
    boxMm: { min: [-4.96, -5, -4], max: [4.96, 5, 16] },
  },
  {
    uid: '0.63.D06912.06020',
    family: 'din7984',
    size: 'M6',
    length: 20,
    stlUrl: '/fasteners/0.63.D06912.06020.stl',
    boxMm: { min: [-5, -5, -4], max: [5, 5, 20] },
  },
  {
    uid: '0.63.D06912.06025',
    family: 'din7984',
    size: 'M6',
    length: 25,
    stlUrl: '/fasteners/0.63.D06912.06025.stl',
    boxMm: { min: [-5, -5, -4], max: [5, 5, 25] },
  },
  {
    uid: '0.63.D06912.06030',
    family: 'din7984',
    size: 'M6',
    length: 30,
    stlUrl: '/fasteners/0.63.D06912.06030.stl',
    boxMm: { min: [-4.97, -5, -4], max: [4.97, 4.89, 30] },
  },
  {
    uid: '0.63.D06912.06035',
    family: 'din7984',
    size: 'M6',
    length: 35,
    stlUrl: '/fasteners/0.63.D06912.06035.stl',
    boxMm: { min: [-4.87, -5, -4], max: [4.87, 5, 35] },
  },
  {
    uid: '0.63.D06912.06040',
    family: 'din7984',
    size: 'M6',
    length: 40,
    stlUrl: '/fasteners/0.63.D06912.06040.stl',
    boxMm: { min: [-4.87, -5, -4], max: [4.87, 5, 40] },
  },
  {
    uid: '0.63.D06912.06045',
    family: 'din7984',
    size: 'M6',
    length: 45,
    stlUrl: '/fasteners/0.63.D06912.06045.stl',
    boxMm: { min: [-5, -5, -4], max: [5, 5, 45] },
  },
  {
    uid: '0.63.D06912.06050',
    family: 'din7984',
    size: 'M6',
    length: 50,
    stlUrl: '/fasteners/0.63.D06912.06050.stl',
    boxMm: { min: [-5, -5, -4], max: [5, 5, 50] },
  },
  {
    uid: '0.63.D06912.06055',
    family: 'din7984',
    size: 'M6',
    length: 55,
    stlUrl: '/fasteners/0.63.D06912.06055.stl',
    boxMm: { min: [-4.87, -5, -4], max: [4.87, 5, 55] },
  },
  {
    uid: '0.63.D06912.06060',
    family: 'din7984',
    size: 'M6',
    length: 60,
    stlUrl: '/fasteners/0.63.D06912.06060.stl',
    boxMm: { min: [-4.87, -5, -4], max: [4.87, 5, 60] },
  },
  {
    uid: '0.63.D06912.06085',
    family: 'din7984',
    size: 'M6',
    length: 85,
    stlUrl: '/fasteners/0.63.D06912.06085.stl',
    boxMm: { min: [-4.87, -5, -4], max: [4.87, 5, 85] },
  },
  {
    uid: '0.63.D00912.06012',
    family: 'din912',
    size: 'M6',
    length: 12,
    stlUrl: '/fasteners/0.63.D00912.06012.stl',
    boxMm: { min: [-4.98, -5, -6], max: [4.98, 5, 12] },
  },
  {
    uid: '0.63.D00912.06016',
    family: 'din912',
    size: 'M6',
    length: 16,
    stlUrl: '/fasteners/0.63.D00912.06016.stl',
    boxMm: { min: [-4.96, -5, -6], max: [4.96, 5, 16] },
  },
  {
    uid: '0.63.D00912.06020',
    family: 'din912',
    size: 'M6',
    length: 20,
    stlUrl: '/fasteners/0.63.D00912.06020.stl',
    boxMm: { min: [-5, -5, -6], max: [5, 5, 20] },
  },
  {
    uid: '0.63.D00912.06025',
    family: 'din912',
    size: 'M6',
    length: 25,
    stlUrl: '/fasteners/0.63.D00912.06025.stl',
    boxMm: { min: [-5, -5, -6], max: [5, 5, 25] },
  },
  {
    uid: '0.63.D00912.06030',
    family: 'din912',
    size: 'M6',
    length: 30,
    stlUrl: '/fasteners/0.63.D00912.06030.stl',
    boxMm: { min: [-4.97, -5, -6], max: [4.97, 4.89, 30] },
  },
  {
    uid: '0.63.D00912.06045',
    family: 'din912',
    size: 'M6',
    length: 45,
    stlUrl: '/fasteners/0.63.D00912.06045.stl',
    boxMm: { min: [-4.96, -5, -6], max: [4.96, 4.85, 45] },
  },
  {
    uid: '0.63.D00912.06085',
    family: 'din912',
    size: 'M6',
    length: 85,
    stlUrl: '/fasteners/0.63.D00912.06085.stl',
    boxMm: { min: [-4.87, -5, -6], max: [4.87, 5, 85] },
  },
  {
    uid: '0.63.WN7381.05006',
    family: 'wn7381',
    size: 'M5',
    length: 6,
    stlUrl: '/fasteners/0.63.WN7381.05006.stl',
    boxMm: { min: [-6.65, -6.65, -2.76], max: [6.65, 6.65, 5.99] },
  },
  {
    uid: '0.63.WN7381.05008',
    family: 'wn7381',
    size: 'M5',
    length: 8,
    stlUrl: '/fasteners/0.63.WN7381.05008.stl',
    boxMm: { min: [-6.65, -6.65, -2.76], max: [6.65, 6.65, 7.99] },
  },
  {
    uid: '0.63.WN7381.05012',
    family: 'wn7381',
    size: 'M5',
    length: 12,
    stlUrl: '/fasteners/0.63.WN7381.05012.stl',
    boxMm: { min: [-6.61, -6.65, -2.76], max: [6.61, 6.5, 11.99] },
  },
  {
    uid: '0.63.WN7381.05025',
    family: 'wn7381',
    size: 'M5',
    length: 25,
    stlUrl: '/fasteners/0.63.WN7381.05025.stl',
    boxMm: { min: [-6.6, -6.65, -2.76], max: [6.6, 6.46, 24.99] },
  },
  {
    uid: '0.63.WN7381.06010',
    family: 'wn7381',
    size: 'M6',
    length: 10,
    stlUrl: '/fasteners/0.63.WN7381.06010.stl',
    boxMm: { min: [-7.35, -7.35, -3.31], max: [7.35, 7.35, 9.99] },
  },
  {
    uid: '0.63.WN7381.06012',
    family: 'wn7381',
    size: 'M6',
    length: 12,
    stlUrl: '/fasteners/0.63.WN7381.06012.stl',
    boxMm: { min: [-7.31, -7.35, -3.31], max: [7.31, 7.19, 11.99] },
  },
  {
    uid: '0.63.WN7381.06016',
    family: 'wn7381',
    size: 'M6',
    length: 16,
    stlUrl: '/fasteners/0.63.WN7381.06016.stl',
    boxMm: { min: [-7.31, -7.35, -3.31], max: [7.31, 7.19, 15.99] },
  },
  {
    uid: '0.63.WN7381.06020',
    family: 'wn7381',
    size: 'M6',
    length: 20,
    stlUrl: '/fasteners/0.63.WN7381.06020.stl',
    boxMm: { min: [-7.17, -7.35, -3.31], max: [7.17, 7.35, 19.99] },
  },
];

/** Every baked T-nut — one entry per (family, size); the 30-series block. */
export const T_NUTS: BakedTNut[] = [
  {
    uid: '1.32.4FM4',
    family: 'spring',
    size: 'M4',
    series: 30,
    stlUrl: '/fasteners/1.32.4FM4.stl',
    boxMm: { min: [-5.5, -10, -2.05], max: [5.5, 10, 2.05] },
  },
  {
    uid: '1.32.4FM5',
    family: 'spring',
    size: 'M5',
    series: 30,
    stlUrl: '/fasteners/1.32.4FM5.stl',
    boxMm: { min: [-5.5, -10, -2.05], max: [5.5, 10, 2.05] },
  },
  {
    uid: '1.32.4FM6',
    family: 'spring',
    size: 'M6',
    series: 30,
    stlUrl: '/fasteners/1.32.4FM6.stl',
    boxMm: { min: [-5.5, -10, -2.05], max: [5.5, 10, 2.05] },
  },
  {
    uid: '1.34.10EM4',
    family: 't_slot',
    size: 'M4',
    series: 30,
    stlUrl: '/fasteners/1.34.10EM4.stl',
    boxMm: { min: [-3.85, -7.75, -3], max: [3.85, 7.75, 3] },
  },
  {
    uid: '1.34.10EM5',
    family: 't_slot',
    size: 'M5',
    series: 30,
    stlUrl: '/fasteners/1.34.10EM5.stl',
    boxMm: { min: [-3.85, -7.75, -3], max: [3.85, 7.75, 3] },
  },
  {
    uid: '1.34.10EM6',
    family: 't_slot',
    size: 'M6',
    series: 30,
    stlUrl: '/fasteners/1.34.10EM6.stl',
    boxMm: { min: [-3.85, -7.75, -3], max: [3.85, 7.75, 3] },
  },
];

const screwIndex = new Map(SCREWS.map((s) => [`${s.family}|${s.size}|${s.length}`, s]));
const tnutIndex = new Map(T_NUTS.map((t) => [`${t.family}|${t.size}|${t.series}`, t]));

/** The families that hold `size`, in the catalog's own order. */
export function screwFamiliesFor(size: ScrewSize): ScrewFamily[] {
  const order: ScrewFamily[] = ['din912', 'din7984', 'countersunk', 'wn7381'];
  return order.filter((f) => SCREWS.some((s) => s.family === f && s.size === size));
}

/** Every nominal length the catalog holds for (family, size), ascending. */
export function screwLengths(family: ScrewFamily, size: ScrewSize): number[] {
  return SCREWS.filter((s) => s.family === family && s.size === size).map((s) => s.length);
}

/**
 * The part for (family, size, length).
 *
 * `length` is snapped to the NEAREST baked nominal rather than rejected: every
 * caller (seats, panels, BOM, and layouts stored before this table existed) can
 * then name a length the catalog does not hold without the lookup going missing
 * and the part silently failing to draw.
 */
export function findScrew(family: ScrewFamily, size: ScrewSize, length: number): BakedScrew {
  const exact = screwIndex.get(`${family}|${size}|${length}`);
  if (exact) return exact;
  const all = SCREWS.filter((s) => s.family === family && s.size === size);
  const pool = all.length ? all : SCREWS.filter((s) => s.size === size);
  const seed = pool.length ? pool : SCREWS;
  return seed.reduce((best, s) =>
    Math.abs(s.length - length) < Math.abs(best.length - length) ? s : best, seed[0]);
}

/**
 * The T-nut for (family, size, series); an unbaked series falls back to the
 * nearest one WITHIN the family.
 *
 * `family` is defaulted rather than required so the plain block stays the
 * answer for a caller that only ever meant "a T-nut": the catalog holds an M6
 * in both families for the same slot, so a bare (size, series) lookup would
 * otherwise be free to return the spring nut to a kit that never asked for it.
 */
export function findTNut(size: ScrewSize, series: number, family: TNutFamily = 't_slot'): BakedTNut {
  const exact = tnutIndex.get(`${family}|${size}|${series}`);
  if (exact) return exact;
  const pool = T_NUTS.filter((t) => t.family === family && t.size === size);
  const seed = pool.length ? pool : T_NUTS.filter((t) => t.family === family);
  const fallback = seed.length ? seed : T_NUTS;
  return fallback.reduce((best, t) =>
    Math.abs(t.series - series) < Math.abs(best.series - series) ? t : best, fallback[0]);
}

/**
 * The default length for (family, size): the shortest catalog length whose shaft
 * can still do the job the app puts a bolt to — through a bracket plate and ~8 mm
 * into the T-nut — i.e. 12 mm. Falls back to the longest on offer.
 */
export const DEFAULT_SHAFT_MM = 12;
export function defaultScrewLength(family: ScrewFamily, size: ScrewSize): number {
  const lens = screwLengths(family, size);
  return lens.find((l) => l >= DEFAULT_SHAFT_MM) ?? lens[lens.length - 1];
}
