// GENERATED by scripts/bake_scene_textures.py — do not edit by hand.
// Re-run that script instead; it writes both the PNGs and this table.

export interface SceneTexture {
  id: string;
  /** sRGB — a colour map, read as colour. */
  colorUrl: string;
  /** LINEAR data (three: NoColorSpace). Never read a roughness map as sRGB. */
  roughUrl: string;
  /** Millimetres of surface the tile covers, both ways. The scene's UVs are
   *  authored in these units (millimetres / tileMm) with `texture.repeat`
   *  left alone, so the tile size has to live beside the image it describes. */
  tileMm: number;
  /** What is drawn while the PNG loads, and if it never arrives at all. */
  color: string;
}

export const SCENE_TEXTURES: SceneTexture[] = [
  {
    id: "floor_oak",
    colorUrl: "/textures/floor_oak_color.png",
    roughUrl: "/textures/floor_oak_rough.png",
    tileMm: 1600,
    color: "#a8814f",
  },
  {
    id: "wall_plaster",
    colorUrl: "/textures/wall_plaster_color.png",
    roughUrl: "/textures/wall_plaster_rough.png",
    tileMm: 1200,
    color: "#ded9cf",
  },
  {
    id: "floor_concrete",
    colorUrl: "/textures/floor_concrete_color.png",
    roughUrl: "/textures/floor_concrete_rough.png",
    tileMm: 1200,
    color: "#8c8b87",
  },
  {
    id: "rug_weave",
    colorUrl: "/textures/rug_weave_color.png",
    roughUrl: "/textures/rug_weave_rough.png",
    tileMm: 500,
    color: "#b3a894",
  },
];

export function sceneTextureById(id: string): SceneTexture | undefined {
  return SCENE_TEXTURES.find((t) => t.id === id);
}
