// GENERATED by scripts/bake_tabletop_textures.py — do not edit by hand.
// Re-run that script instead; it writes both the PNGs and this table.

export interface TabletopTexture {
  id: string;
  label: string;
  /** One line for the picker: what you are looking at. */
  note: string;
  /** Swatch tint, and what is drawn if the PNG never arrives. */
  color: string;
  faceUrl: string;
  /** Millimetres of board `faceUrl` covers, both ways. */
  faceTileMm: number;
  /** The same material seen end-on, and how many mm of it the tile spans:
   *  [along the edge, through the thickness]. */
  edgeUrl: string;
  edgeTileMm: [number, number];
  /** LINEAR data (three: NoColorSpace) — never read a roughness map as sRGB. */
  faceRoughUrl: string;
  edgeRoughUrl: string;
  /** How the tile repeats. Omitted means 'repeat', which is seamless for
   *  everything baked here — the wrap-aware noise above guarantees it. It is
   *  set for UPLOADED boards only: a photograph is not tileable, and mirroring
   *  turns a hard seam into a fold the eye reads as more grain. */
  wrap?: 'repeat' | 'mirror';
}

export const FACE_TILE_MM = 600;

export const TABLETOP_TEXTURES: TabletopTexture[] = [
  {
    id: "oak",
    label: "橡木",
    note: "直纹 · 年轮细密，导管孔在光下发暗",
    color: "#85745b",
    faceUrl: "/textures/oak_color.png",
    faceRoughUrl: "/textures/oak_rough.png",
    faceTileMm: 600,
    edgeUrl: "/textures/oak_color.png",
    edgeRoughUrl: "/textures/oak_rough.png",
    edgeTileMm: [600, 600],
  },
  {
    id: "walnut",
    label: "黑胡桃",
    note: "直纹 · 色深，年轮宽、明暗对比强",
    color: "#503925",
    faceUrl: "/textures/walnut_color.png",
    faceRoughUrl: "/textures/walnut_rough.png",
    faceTileMm: 600,
    edgeUrl: "/textures/walnut_color.png",
    edgeRoughUrl: "/textures/walnut_rough.png",
    edgeTileMm: [600, 600],
  },
  {
    id: "plank",
    label: "橡木拼板",
    note: "宽窄不一的板条胶拼 · 接缝处的胶线比木头更光",
    color: "#85745b",
    faceUrl: "/textures/plank_color.png",
    faceRoughUrl: "/textures/plank_rough.png",
    faceTileMm: 600,
    edgeUrl: "/textures/plank_color.png",
    edgeRoughUrl: "/textures/plank_rough.png",
    edgeTileMm: [600, 600],
  },
  {
    id: "ply",
    label: "多层板",
    note: "薄面皮 + 侧边一叠胶合层 · 层厚按毫米固定，不随板厚变",
    color: "#8d7e64",
    faceUrl: "/textures/ply_color.png",
    faceRoughUrl: "/textures/ply_rough.png",
    faceTileMm: 600,
    edgeUrl: "/textures/ply_edge_color.png",
    edgeRoughUrl: "/textures/ply_edge_rough.png",
    edgeTileMm: [300, 20],
  },
];

export const DEFAULT_TABLETOP_TEXTURE = 'oak';

// The by-id lookup deliberately does NOT live here. It is not a fact about
// the baked images; it is the one resolution point for the whole pipeline,
// and it has to be able to see boards that exist only at runtime (uploads).
// See src/materials/boardRegistry.ts — boardById().
